server: "qbrp"

chat:
  channels:
    default:
      format: "{l} {author_name} : {text}"
      speech: true
      heads: true

    global:
      format: "{g} {author_name} : {text}"
      speech: true
      heads: true

  commands:
    me:
      format: "{author_name} * {text}"
      distance: 12
      regex:
        exp: '^\*\*.*\*\*$'
        remove: '\*\*'
      heads: true

  placeholders:
    g: "<aqua><bold>ɢ</bold></aqua>"
    l: "<yellow><bold>ʟ</bold></yellow>"

  default-channel: "default"

  pm: "{author_name} -> {pm_receiver_name}: {text}"

  acoustic:
    passability:
      solid: 0.0
      partial: 0.95
      air: 0.99
      tags:
        "test": 1
      blocks:
        "minecraft:sand": 0.5
    formatting:
      - volume: 1
    distortion:
      threshold: 0.3
      artifacts: [ '-', '~' ]
    simulation:
      steps: 100
      chunk-size: 18
      range: 24
      performance-debug: true
    volume:
      max: 1.5
      hearing-threshold: 0.05
      easing: 0.98

  advancements: false

  join:
    enabled: false
    message: ""
  leave:
    enabled: false
    message: ""

player:
  volume:
    min: 0.3
    base: 0.5
    max: 1.2
  attributes:
    default:
      speed: 0.15
      jump-strength: 0.45
    gm:
      speed: 0.24
      jump-strength: 0.45
    spectator:
      speed: 0.15
  damage: true

vocal:
  # При каком значении усталости возможно сорвать голос
  break_threshold: 0.3
  # Шанс сорвать голос при максимальной усталости
  break_chance: 0.1
  # Время восстановления голоса при срыве в секундах
  regeneration_time: 700
  # Случайный разброс времени
  regeneration_random: 0.5

  # Выше какой громкости голосовой аппарат начинает уставать
  tiredness_threshold: 0.6
  # Усиление усталости голоса при полной громкости (до 1)
  tiredness_gain: 0.125
  # Уменьшение усталости голоса в секунду (при 0.33 выходит 600 секунд, примерно 10 минут)
  tiredness_decrease_rate: 0.0033

movement:
  # Множитель скорости в режиме бега
  sprint_multiplier: 1.5
  # Множитель к показателю аттрибута скорости, определяющий самую низкую возможную скорость (от 0 до 1)
  min_speed_factor: 0.05
  # Минимально возможная скорость при беге, работает как минимальный ограничитель множителя регулируемой игроком скорости
  min_speed_multiplier_sprint_factor: 0.3
  # Порог стамины, при котором персонаж начинает замедляться
  slowdown_stamina_threshold: 0.3
  # Уменьшение стамины за 1 минуту тик при максимальной скорости
  stamina_consumption: 5.9
  # Постоянное (!) восстановление стамины за 1 минуту. Стамина тратится, когда потребление становится больше регенерации
  stamina_regen: 3.6
  # Как сильно скорость, регулируемая игроков, влияет на реальную скорость персонажа (по сути, ограничитель)
  intention_effect: 0.7
